### ISSUE TITLE
请问 证书文件缺失  如何修复

### ISSUE THREAD

**Issue by yuwangi** [WinWang/HarmoneyOpenEye#13]
![image](https://github.com/WinWang/HarmoneyOpenEye/assets/13346477/36868d4e-0d77-49b9-9dbe-3bbbc6d707ad)

**Comment by WinWang** [comment]
删除掉module.json5里面的签名配置就好了

**Comment by qidianwei** [comment]
想问一下，具体删哪个呢？

**Comment by WinWang** [comment]
<img width="1654" alt="image" src="https://github.com/WinWang/HarmoneyOpenEye/assets/19348069/651355ce-290f-4a2e-89dc-61d210e123ec">
