### ISSUE TITLE
axios网络请求的封装的自定义header怎么设置？

### ISSUE THREAD

**Issue by lishide** [WinWang/HarmoneyOpenEye#19]
axios网络请求的封装的自定义header怎么设置？请给个示例，比如设置token等

**Comment by WinWang** [comment]
<img width="993" alt="image" src="https://github.com/WinWang/HarmoneyOpenEye/assets/19348069/ceff2adc-f5e6-43e5-afca-a0e887e1a185">

**Comment by lishide** [comment]
commonHeader 在哪声明的，需要设置多个呢？

**Comment by WinWang** [comment]
commonHeader就是普通一个AxiosHeader的对象。 let commonHeader = new AxiosHeader()      你说的设置多个是什么意思？commonHeader.set可以多次调用的，例如set（“Token”），set("PhoneType")等

**Comment by lishide** [comment]
好的，感谢
