### ISSUE TITLE
针对单独接口进行catch处理，比如这个接口报错了，弹窗处理

### ISSUE THREAD

**Issue by JasonYinH** [WinWang/HarmoneyOpenEye#21]
那如果单独针对某个接口处理catch，咋搞
![473592977b4ff2570599efd84ee0c5a](https://github.com/WinWang/HarmoneyOpenEye/assets/40187930/b6f0960c-4e5a-4417-9aad-593d73c29c47)
![a341a8731f99a5cdf008760a5ae6142](https://github.com/WinWang/HarmoneyOpenEye/assets/40187930/3a639208-ae6d-4e3e-a432-fbac468e8e2e)
![fb3a22077b897fb45d2d1f706ea06a7](https://github.com/WinWang/HarmoneyOpenEye/assets/40187930/6b84493c-147e-4571-a79f-8168c2382865)
直接这样吗
![a3fc9df604ff3f70d428461d3ae86a3](https://github.com/WinWang/HarmoneyOpenEye/assets/40187930/a0092ef4-70fb-4472-8b62-481e4f4f7a8f)

**Comment by WinWang** [comment]
<img width="1003" alt="image" src="https://github.com/WinWang/HarmoneyOpenEye/assets/19348069/27461d55-0166-41d0-bb08-586bef1298d6">
<img width="729" alt="image" src="https://github.com/WinWang/HarmoneyOpenEye/assets/19348069/b06baa78-dbe7-4f93-9717-f5c0ecf73b2d">
参照这样用就好了

**Comment by JasonYinH** [comment]
感谢佬
